### ISSUE TITLE
Support for streams

### ISSUE THREAD

**Issue by pspi** [bendrucker/postgres-bytea#7]
Our use case is to save and read images stored in bytea values from Postgres. Performance-wise, it's better to stream the data instead of collecting it to a buffer.

Would you be open to a PR that would add support for streams to this library? It'd be a Transform stream that would read one format and output the converted format. Or, would see that implementation in a separate library, instead? To guide users, the separate library could be named after this library, for example 'postgres-bytea-streams'.

To make the API complete, the plan is to implement streaming both ways:
1. "binary" -> "bytea hex format"
2. "bytea hex format" -> "binary" 

As currently this module supports only converting "bytea hex format" string to "binary" buffers, for symmetry, a buffer-version of "binary" -> "bytea hex format" conversion would be added, too.

What do you think?

**Comment by pspi** [comment]
Hmm, I tried to play around with this module and I'm not sure it converts "bytea hex format" string to "binary" buffer anymore. Could you help me understand what this module does?

I'm referring to the bytea hex format described here https://www.postgresql.org/docs/12/datatype-binary.html . It presents raw binary data in hex format where the resulting string is prefixed with '\x'.

Edit. It might be to do with double escaping the beginning '\\', which is needed in many applications
- since `bytea('\\\\x61').toString() // => '\\x61'`, produced weird result
- but `bytea('\\x61').toString() // => 'a'` which is correct

**Comment by bendrucker** [comment]
Hi, yes it's mainly dealing with with escaping. It is primary used as a bytea column parser when you `require('pg')`:

https://github.com/brianc/node-pg-types/blob/b96a92e0871c0f0611bc3fd97c4d12d239f6fffa/lib/textParsers.js#L4

Happy to consider a PR here particularly if it's non-breaking!

**Comment by pspi** [comment]
This is now fixed with https://github.com/bendrucker/postgres-bytea/pull/9 and can be closed.
